spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:25432/payments
    username: payments
    password: payments

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /

server:
  port: 7777

payments:
  timezone: "Europe/Vilnius"

---
spring:
  profiles: test
  datasource:
    url: jdbc:postgresql://127.0.0.1:25432/payments_test
