# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:9.6.1
        env:
          POSTGRES_DB: payments_test
          POSTGRES_USER: payments
          POSTGRES_PASSWORD: payments
        # wait for postgres is up
        options: >-
          --health-cmd pg_isready
          --health-interval 2s
          --health-timeout 5s
          --health-retries 15
        ports:
          - 25432:5432

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup cache
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Maven
      run: mvn -B verify

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Manual Push to Docker Hub
      run:
        docker push tikrai/payments

#    - name: Push to Docker Hub
#      uses: docker/build-push-action@v1
#      env:
#        JAR_FILE: payments-0.0.1.jar
#      with:
#        username: ${{ secrets.DOCKER_USERNAME }}
#        password: ${{ secrets.DOCKER_PASSWORD }}
#        repository: tikrai/payments
#        tag_with_ref: true
#
#    - name: Debug
#      env:
#        ZAZA_FILE: payments-0.0.1.jar
#      run: |
#        ls -la
#        echo ===============================================
#        echo $JAR_FILE
#        echo ===============================================
#        ls target -la
#        echo ===============================================
#        echo $ZAZA_FILE

